name: homework_11
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.3.0
  dart_code_metrics: ^5.7.4
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_hotreload: ^1.4.0
  shelf_helmet: ^2.0.0
  supabase: ^1.8.1
  dart_jsonwebtoken: ^2.7.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
