name: hw11_team2
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

dependencies:
  args: ^2.4.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_hotreload: ^1.4.0
  dart_code_metrics: ^5.7.4
  supabase: ^1.9.0
  dart_jsonwebtoken: ^2.7.1
  


dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
